import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import NavBar from "./components/NavBar";

import ClientLayout from './client-layout';

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  console.log('RootLayout rendered on client');
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900 min-h-screen transition-colors duration-500`}
        style={{ backgroundAttachment: 'fixed' }}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
